// This file will be auto-generated by Supabase CLI in Phase 10.
// Command: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.types.ts
export type Database = Record<string, unknown>;
